name: 'Robert Dimitrov'
markdown: redcarpet
highlighter: pygments
url:    'http://robbdimitrov.com'
author: 'Robert Dimitrov'

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false
safe:     true
encoding:     "utf-8"
